language: minimal

services:
  - docker

script:
  - docker-compose build -f docker-compose-build.yaml --parallel
  - docker tag udagram-api-feed kienndt/udagram-api-feed:v1
  - docker tag udagram-api-user kienndt/udagram-api-user:v1
  - docker tag udagram-frontend:local kienndt/udagram-frontend:v1
  - docker tag udagram-reverseproxy kienndt/udagram-reverseproxy:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kienndt/udagram-api-feed:v1
  - docker push kienndt/udagram-api-user:v1
  - docker push kienndt/udagram-frontend:v1
  - docker push kienndt/udagram-reverseproxy:v1
