apiVersion: v1
kind: Service
metadata:
  name: frontend-custom
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8110
    targetPort: 80
    nodePort: 32001
  selector:
    app: frontend-custom
