apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-custom
  template:
    metadata:
      labels:
        app: frontend-custom
    spec:
      containers:
      - name: frontend-custom
        image: frontend-custom:local
        ports:
        - containerPort: 80
        env:
          - name: API_GATEWAY_HOST
            value: reverseproxy